# Generated by Django 4.1.7 on 2023-03-10 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("sending", "sending"),
                            ("sent", "sent"),
                            ("error", "error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
